export const PropertyDb: PropertySearchResult[] = [
  {
    name: 'Test Apartment',
    image: '/trump.jpg',
    score: 9,
    price: 9999,
    discount: 50,
    nbr_of_reviews: 20,
    additional_label: 'ONLY 2 LEFT',
    free_cancellation: true,
  },
  {
    name: 'My hotel',
    image: '/biden.jpg',
    score: 10,
    price: 1000,
    discount: 0,
    nbr_of_reviews: 40482,
    additional_label: 'YAY',
    free_cancellation: true,
  },
  {
    name: 'hotel',
    image: '/prayut.jpg',
    score: 8.9,
    price: 20,
    discount: 0,
    nbr_of_reviews: 20,
    additional_label: 'WRITE ANYTHING HERE',
    free_cancellation: true,
  },
  {
    name: 'anya\'s secret base',
    image: '/anya.gif',
    score: 99.9,
    price: 9999999,
    discount: 99,
    nbr_of_reviews: 20,
    additional_label: 'โครงการคนละครึ่ง',
    free_cancellation: true,
  },
    name: 'pas team',
    image: 'https://www.google.co.th/images/branding/googlelogo/1x/googlelogo_light_color_272x92dp.png',
    score: 30,
    price: 20000000.50,
    discount: 30,
    nbr_of_reviews: 20,
    additional_label: 'WRITE ANYTHING HERE',
    free_cancellation: true,
  },
    name: 'natchanon tower 969',
    image: '/biden.jpg',
    score: 100,
    price: 20,
    discount: 0,
    nbr_of_reviews: 20,
    additional_label: 'promotion',
    free_cancellation: true,
  },
    name: 'Galaxy Hotel',
    image: '/biden.jpg',
    score: 8.9,
    price: 20,
    discount: 0,
    nbr_of_reviews: 20,
    additional_label: 'Eieiza haha plus',
    free_cancellation: true,
  }
];
