export const PropertyDb: PropertySearchResult[] = [
  {
    name: 'Test Apartment',
    image: '/trump.jpg',
    score: 9,
    price: 9999,
    discount: 50,
    nbr_of_reviews: 20,
    additional_label: 'ONLY 2 LEFT',
    free_cancellation: true,
  },
  {
    name: 'aaaaaaa',
    image: '/biden.jpg',
    score: 8.9,
    price: 20,
    discount: 0,
    nbr_of_reviews: 20,
    additional_label: 'WRITE ANYTHING HERE',
    free_cancellation: true,
  },
  {
    name: 'Balloon Hotel',
    image: '/biden.jpg',
    score: 8.9,
    price: 20,
    discount: 0,
    nbr_of_reviews: 20,
    additional_label: 'WRITE ANYTHING HERE',
    free_cancellation: true,
  },
  {
    name: 'Rotii Hotel',
    image: '/rotii.jpg',
    score: 10.0,
    price: 340,
    discount: 10,
    nbr_of_reviews: 200,
    additional_label: 'Come here free wifi',
    free_cancellation: false,
  },
];
