export const PropertyDb: PropertySearchResult[] = [
  {
    name: "Test Apartment",
    image: "/trump.jpg",
    score: 9,
    price: 9999,
    discount: 50,
    nbr_of_reviews: 20,
    additional_label: "ONLY 2 LEFT",
    free_cancellation: true,
  },
  {
    name: "aaaaaaa",
    image: "/biden.jpg",
    score: 8.9,
    price: 20,
    discount: 0,
    nbr_of_reviews: 20,
    additional_label: "WRITE ANYTHING HERE",
    free_cancellation: true,
  },
  {
    name: "fxhkewie",
    image: "/orcat.jpeg",
    score: 10,
    price: 99999,
    discount: 60,
    nbr_of_reviews: 40,
    additional_label: "ONLY 1 LEFT",
    free_cancellation: true,
  },
];
