- uses: actions/checkout@v3
- name: Login to GitHub Container Registry
  uses: docker/login-action@v2
  with:
    username: ${{ secrets.DOCKERHUB_USER }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}
on:
  pull_request:
    branches: [main]
