name: main

on:
  push:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 
          - encx/agoda-ci-workshop-dryrun:latest
          - encx/agoda-ci-workshop-dryrun:1.0.${{ github.run_id }}
