name: pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn
      - run: yarn build
      - run: RUNNER_TRACKING_ID="" && (nohup yarn start&)
      - run: npx playwright install
      - run: yarn test:e2e
